/**
 * Fetches the OpenAPI spec from the Chatterbox TTS API and generates TypeScript types.
 *
 * Usage:
 *   CHATTERBOX_API_URL=https://your-api-url npm run sync-api
 *
 * Or with .env file:
 *   npm run sync-api
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import "dotenv/config";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = path.resolve(__dirname, "../src/types/chatterbox-api.d.ts");

async function main() {
  const apiUrl = process.env.CHATTERBOX_API_URL;

  if (!apiUrl) {
    console.error("Error: CHATTERBOX_API_URL environment variable is required");
    process.exit(1);
  }

  const openApiUrl = `${apiUrl}/openapi.json`;
  console.log(`Fetching OpenAPI spec from: ${openApiUrl}`);

  const ast = await openapiTS(new URL(openApiUrl));
  const contents = astToString(ast);

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Add header comment
  const header = `/**
* This file is auto-generated by scripts/sync-api.ts
* Do not edit manually. Run \`npm run sync-api\` to regenerate.
*
* Generated from: ${openApiUrl}
* Generated at: ${new Date().toISOString()}
*/
  `;

  fs.writeFileSync(OUTPUT_PATH, header + contents);
  console.log(`Types written to: ${OUTPUT_PATH}`);
}

main().catch((err) => {
  // Check if this is a network/404 error (e.g. Modal server scaled down)
  const is404 = String(err).includes("404");
  if (is404 && fs.existsSync(OUTPUT_PATH)) {
    console.warn(
      "\n⚠️  Could not reach the API server (404). This usually means the Modal server is scaled down."
    );
    console.warn(`   Using existing local types at: ${OUTPUT_PATH}`);
    console.warn(
      "   To regenerate, deploy the server first, then re-run this script.\n"
    );
    process.exit(0);
  }

  console.error("Failed to sync API types:", err);
  process.exit(1);
});